# Generated by Django 5.1.6 on 2025-02-22 17:51

from django.db import migrations

def create_user_profile(apps, schema_editor):
    User = apps.get_model('auth', 'user')
    UserProfile = apps.get_model('budget', 'UserProfile')

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_userprofile'),
    ]

    operations = [
    ]
