# Generated by Django 5.1.6 on 2025-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_create_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
